== Sealed Classes (JDK 17)

** Sealed classes provide a fine-grained inheritance control in Java
** Prior to sealed classes, every non-final class could be extended by any number of sub-classes
** With sealed classes we get the following modifiers and clauses
*** `sealed`: A sealed class or interface can be extended of implemented only by those classes and interfaces permitted to do so.
*** `non-sealed`: The `non-sealed` modifier allows to open up a part of the hierarchy without exposing the entire hierarchy.
*** `permits`: The `permits` clause specified the subclasses that can extend the sealed class.
** If subclasses are in different files in the same module or package, then use `permits` to define the subclasses that may extend the sealed class
** If subclasses are in the same file as `sealed` superclass, then `permits` clause is not needed

--
.Sealed Interface
[source,java,highlight=2..3]
----
public sealed interface User permits Owner, Admin, Resident {
    default String login() {
        return "Logged in";
    }
}

----

--

.Final Class
[source,java,highlight=2..3]
----
public final class Owner implements User {
}

----

--
.Sealed Class
[source,java,highlight=2..3]
----
public sealed class Admin implements User permits SuperAdmin {
}

----

--

.Inherited from sealed Class
[source,java,highlight=2..3]
----
public final class SuperAdmin extends Admin {
}
// This test passes
Assertions.assertEquals("Logged in", superAdmin.login());

// Below class TempAdmin does not compile as TempAdmin is not permitted in the sealed hierarchy
public final class TempAdmin extends Admin {
}
----

--
.Non-Sealed Class
[source,java,highlight=2..3]
----
public non-sealed class Resident implements User  {
}
----

--

.Inherited from non-sealed Class
[source,java,highlight=2..3]
----
// Since Resident is non-sealed, it is open for any number of sub-classes, hence it opens up the hierarchy
public final class DayGuest extends Resident {
}

public final class OvernightGuest extends Resident {
}

// These tests passed
Assertions.assertEquals("Logged in", dayGuest.login());
Assertions.assertEquals("Logged in", overnightGuest.login());
----